# Generated by Django 4.2.11 on 2024-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.IntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('siret_number', models.IntegerField()),
                ('siren_number', models.IntegerField()),
                ('affaire', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=10)),
                ('intermediaire', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('coassurance', models.BooleanField(default=False)),
                ('operation_adresse', models.CharField(max_length=255)),
                ('operation_description', models.TextField()),
                ('price_operation', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
