# Generated by Django 4.2.11 on 2024-05-05 15:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='opportunity_number',
            field=models.IntegerField(verbose_name="Numéro d'opportunité"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='short_description',
            field=ckeditor.fields.RichTextField(verbose_name='Courte description'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='siren_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro SIREN'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='siret_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro SIRET'),
        ),
    ]
