# Generated by Django 4.2.11 on 2024-05-05 18:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_alter_projet_image_alter_projet_opportunity_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='operation_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projet',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Courte description'),
        ),
    ]
