# Generated by Django 4.2.11 on 2024-05-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0005_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentProjet',
        ),
    ]
