# Generated by Django 4.2.11 on 2024-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0006_rename_document_documentprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprojet',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='docx_files'),
        ),
        migrations.AlterField(
            model_name='documentprojet',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files'),
        ),
    ]
