# Generated by Django 4.2.11 on 2024-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0008_alter_documentprojet_docx_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='docx_files/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
        migrations.DeleteModel(
            name='DocumentProjet',
        ),
    ]
