# Generated by Django 4.2.11 on 2024-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0012_remove_planimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='opportunity_number',
            field=models.IntegerField(verbose_name="Numéro d'opportunité"),
        ),
    ]
